version: '3.4'

services:
  worldtextingfoundationapi:
    image: worldtextingfoundationapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1339:1339
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
